apiVersion: v1
kind: Secret
metadata:
  name: keda-sb-queue-secret
  namespace: sbx-app-keda-example
  labels:
    app: go-consumer-app
type: Opaque
data:
  # TODO: base64 encoded connection string, refactor Azure Secret CSI driver to support connection string
  sbConnectionString: INSERTSTRING
